# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Core'

# Event for the workflow
on: 
  push:
    paths:
      - packages/core/**

# List of jobs
jobs:
  chromatic-core-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # ðŸ‘‡ Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
      - name: build
        run: npx lerna run build --scope=@theme-toggles/core
        # ðŸ‘‡ Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # ðŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_CORE }}
          workingDir: ./packages/core
